When I set the `default_timezone` to `Asia/Shanghai` and initiate a backfill command, the following exception is thrown:

```python
return func(*args, session=session, **kwargs)
File "/usr/local/lib/python3.6/site-packages/airflow/models/dagrun.py", line 181, in refresh_from_db
    DR.run_id == self.run_id,
File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

Switching back to the default timezone resolves the issue.