When I configure my default_timezone as Asia/Shanghai and kick off backfill
command, it throws exceptions:
    return func(*args, session=session, **kwargs)
File "/usr/local/lib/python3.6/site-packages/airflow/models/dagrun.py", line
181, in refresh_from_db  
DR.run_id == self.run_id,  
File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line
3500, in one  
raise orm_exc.NoResultFound("No row was found for one()")  
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
Changing back to default timezone works again.