A clear and concise description of what the bug is.
### Process
  1. Using Ubuntu 22.04.5, MiniConda, Python3.8
  2. install superset
  3. superset db upgrade
### Actual results
    Traceback (most recent call last):
      File "/home/chick/miniconda3/envs/py38/bin/superset", line 5, in 
        from superset.cli.main import superset
      File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/__init__.py", line 21, in 
        from superset.app import create_app
      File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/app.py", line 23, in 
        from superset.initialization import SupersetAppInitializer
      File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/initialization/__init__.py", line 33, in 
        from superset.extensions import (
      File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/extensions/__init__.py", line 32, in 
        from superset.utils.cache_manager import CacheManager
      File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/utils/cache_manager.py", line 24, in 
        from superset.utils.core import DatasourceType
      File "/home/chick/miniconda3/envs/py38/lib/python3.8/site-packages/superset/utils/core.py", line 76, in 
        from cryptography.hazmat.backends.openssl.x509 import _Certificate
    ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.x509'
### Environment
  * Ubuntu 22.04.5,
  * MiniConda,
  * Python3.8